pluginManagement {
    plugins {
        id "org.jetbrains.kotlin.plugin.lombok" version '2.3.21'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = 'cloudpvp'
include 'cloudpvp-core'

include 'cloudpvp-auth'
include 'cloudpvp-beans'
include 'cloudpvp-gateway'
include 'cloudpvp-lobby'
include 'cloudpvp-play'
include 'cloudpvp-state'
include 'cloudpvp-user-summary'
